Fixed bug that caused subscriptions to continuous query tasks to fail
The bug was that if a client made a subscription to a continuous query
task and requested that it replay the state, it could fail to send the
notification with the replayed state. Internally, there was a kryo
exception: Class cannot be created (missing no-arg constructor)

The fix was to not clone the replayed state.

Change-Id: I61b80016bb63bca10211475a9640a4a5d37290f6